import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'

const en = {
  nav: { home: 'Home', store: 'Store', login: 'Login', register: 'Register', account: 'Account', logout: 'Logout' },
  home: { hero: 'Get Your PUBG UC Instantly', subtitle: 'Fast, secure, and reliable UC codes delivered automatically', cta: 'Browse Store', features: 'Why Choose Us', feature1: 'Instant Delivery', feature1Desc: 'Get your UC code immediately after purchase', feature2: 'Secure Payments', feature2Desc: 'Your transactions are safe with us', feature3: '24/7 Support', feature3Desc: 'We are here to help anytime', howItWorks: 'How It Works', step1: 'Create Account', step2: 'Add Funds', step3: 'Purchase UC', step4: 'Get Code' },
  auth: { email: 'Email', name: 'Name', password: 'Password', confirmPassword: 'Confirm Password', login: 'Login', register: 'Create Account', noAccount: "Don't have an account?", hasAccount: 'Already have an account?', loginHere: 'Login here', registerHere: 'Register here' },
  store: { title: 'UC Packages', uc: 'UC', buy: 'Buy Now', available: 'Available', outOfStock: 'Out of Stock', playerId: 'Player ID', confirm: 'Confirm Purchase', success: 'Purchase Successful!', code: 'Your Code', insufficientBalance: 'Insufficient balance', emptyTitle: 'No Products Available', emptyDesc: 'No products have been added yet. Please wait for the store owners to add products.' },
  account: { overview: 'Overview', orders: 'Orders', wallet: 'Wallet', settings: 'Settings', balance: 'Balance', addFunds: 'Add Funds', amount: 'Amount', transactionId: 'Transaction ID', submit: 'Submit', pending: 'Pending', approved: 'Approved', rejected: 'Rejected', language: 'Language', changePassword: 'Change Password', currentPassword: 'Current Password', newPassword: 'New Password', save: 'Save', noOrders: 'No orders yet', orderHistory: 'Order History' },
  notifications: { title: 'Notifications', markAllRead: 'Mark all as read', empty: 'No notifications' },
  admin: { dashboard: 'Dashboard', products: 'Products', users: 'Users', deposits: 'Deposits', orders: 'Orders', settings: 'Settings', totalUsers: 'Total Users', totalOrders: 'Total Orders', revenue: 'Revenue', pendingDeposits: 'Pending Deposits', addProduct: 'Add Product', name: 'Name', ucAmount: 'UC Amount', price: 'Price', codes: 'Codes', addCodes: 'Add Codes', approve: 'Approve', reject: 'Reject', edit: 'Edit', delete: 'Delete', actions: 'Actions', status: 'Status', user: 'User', date: 'Date', autoVerify: 'Auto-verify Deposits', autoVerifyDesc: 'Automatically verify Binance payments', apiKey: 'API Key', apiSecret: 'API Secret', connect: 'Connect', disconnect: 'Disconnect', connected: 'Connected', disconnected: 'Disconnected', connecting: 'Connecting...', saveKeys: 'Save & Connect', binanceSettings: 'Binance Settings' }
}

const ar = {
  nav: { home: 'الرئيسية', store: 'المتجر', login: 'تسجيل الدخول', register: 'إنشاء حساب', account: 'حسابي', logout: 'تسجيل الخروج' },
  home: { hero: 'احصل على شدات PUBG فوراً', subtitle: 'أكواد شدات سريعة وآمنة وموثوقة يتم تسليمها تلقائياً', cta: 'تصفح المتجر', features: 'لماذا تختارنا', feature1: 'توصيل فوري', feature1Desc: 'احصل على كود الشدات فور الشراء', feature2: 'دفع آمن', feature2Desc: 'معاملاتك آمنة معنا', feature3: 'دعم 24/7', feature3Desc: 'نحن هنا للمساعدة في أي وقت', howItWorks: 'كيف يعمل', step1: 'إنشاء حساب', step2: 'إضافة رصيد', step3: 'شراء شدات', step4: 'استلام الكود' },
  auth: { email: 'البريد الإلكتروني', name: 'الاسم', password: 'كلمة المرور', confirmPassword: 'تأكيد كلمة المرور', login: 'تسجيل الدخول', register: 'إنشاء حساب', noAccount: 'ليس لديك حساب؟', hasAccount: 'لديك حساب بالفعل؟', loginHere: 'سجل دخول هنا', registerHere: 'سجل هنا' },
  store: { title: 'باقات الشدات', uc: 'شدة', buy: 'اشتري الآن', available: 'متاح', outOfStock: 'نفذت الكمية', playerId: 'معرف اللاعب', confirm: 'تأكيد الشراء', success: 'تم الشراء بنجاح!', code: 'الكود الخاص بك', insufficientBalance: 'رصيد غير كافي', emptyTitle: 'لا توجد منتجات متاحة', emptyDesc: 'لم يتم إضافة أي منتجات حتى الآن. يرجى الانتظار حتى يقوم مالكو الموقع بإضافة المنتجات.' },
  account: { overview: 'نظرة عامة', orders: 'الطلبات', wallet: 'المحفظة', settings: 'الإعدادات', balance: 'الرصيد', addFunds: 'إضافة رصيد', amount: 'المبلغ', transactionId: 'رقم المعاملة', submit: 'إرسال', pending: 'قيد الانتظار', approved: 'موافق عليه', rejected: 'مرفوض', language: 'اللغة', changePassword: 'تغيير كلمة المرور', currentPassword: 'كلمة المرور الحالية', newPassword: 'كلمة المرور الجديدة', save: 'حفظ', noOrders: 'لا توجد طلبات بعد', orderHistory: 'سجل الطلبات' },
  notifications: { title: 'الإشعارات', markAllRead: 'تحديد الكل كمقروء', empty: 'لا توجد إشعارات' },
  admin: { dashboard: 'لوحة التحكم', products: 'المنتجات', users: 'المستخدمين', deposits: 'الإيداعات', orders: 'الطلبات', settings: 'الإعدادات', totalUsers: 'إجمالي المستخدمين', totalOrders: 'إجمالي الطلبات', revenue: 'الإيرادات', pendingDeposits: 'إيداعات معلقة', addProduct: 'إضافة منتج', name: 'الاسم', ucAmount: 'كمية الشدات', price: 'السعر', codes: 'الأكواد', addCodes: 'إضافة أكواد', approve: 'موافقة', reject: 'رفض', edit: 'تعديل', delete: 'حذف', actions: 'الإجراءات', status: 'الحالة', user: 'المستخدم', date: 'التاريخ', autoVerify: 'تحقق تلقائي من الدفعات', autoVerifyDesc: 'التحقق تلقائياً من مدفوعات Binance', apiKey: 'مفتاح API', apiSecret: 'المفتاح السري', connect: 'اتصال', disconnect: 'قطع الاتصال', connected: 'متصل', disconnected: 'غير متصل', connecting: 'جاري الاتصال...', saveKeys: 'حفظ والاتصال', binanceSettings: 'إعدادات Binance' }
}

i18n.use(initReactI18next).init({ resources: { en: { translation: en }, ar: { translation: ar } }, lng: localStorage.getItem('lang') || 'en', fallbackLng: 'en', interpolation: { escapeValue: false } })

export default i18n
